name: pytorch-pix2pix-nifti
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch>=2.0
  - torchvision
  - cudatoolkit=11.8
  - pip
  - pip:
    - dominate
    - Pillow
    - numpy
    - visdom
    - nibabel
    - simpleitk
    - matplotlib
    - evalutils
    - scikit-image