#!/bin/bash
#$ -N test-name
#$ -l h_rt=12:00:00
#$ -l gpu=1
#$ -o /pth_to_/logs/test
#$ -e /pth_to_/logs/test

source path_to_/profile.d/conda.sh
conda activate pytorch-pix2pix-nifti 

cd path_to_repo

python test.py \
    --gpu_ids 0 \
    --dataroot ./path_to_paired_dataset \
    --name test-name \
    --model pix2pix \
    --input_nc 5 \
    --output_nc 5 \
    --netD n_layers \
    --netG unet_256 \
    --dataset_mode nifti \
    --direction BtoA \
    --batch_size 16 \
    --preprocess none \
    --no_flip
